Java hw2t3
katevi/Spbu-homeworks pull request #126
Opened 2019-03-03 21:08 UTC by katevi

2019-03-19 09:40 UTC, ujohnny commented on sem2/hw2/task3/src/main/java/Vinnik/g144/Main.java
> +            output.printSpiral(array);
полиморфизм тут явно недоиспользован

2019-03-19 09:40 UTC, ujohnny commented on sem2/hw2/task3/src/main/java/Vinnik/g144/Print.java
> +    int[] printSpiral(int[][] array) throws FileNotFoundException;
почему у вас generic interface выкидывает filenotfound ?

2019-03-19 09:48 UTC, ujohnny commented on sem2/hw2/task3/src/test/java/Vinnik/g144/SpiralTest.java
> +        for (int i = 0; i < 9; i++) {
почему до 9, а не до result.size() ?

2019-03-19 18:15 UTC, katevi commented on sem2/hw2/task3/src/main/java/Vinnik/g144/Main.java
> +            output.printSpiral(array);
Вы не могли бы пояснить немного точнее, пожалуйста? Я не очень поняла, что нужно исправить.

2019-03-19 18:27 UTC, katevi commented on sem2/hw2/task3/src/main/java/Vinnik/g144/Print.java
> +    int[] printSpiral(int[][] array) throws FileNotFoundException;
Вроде как, если у нас есть два класса, реализующие интерфейс, то интерфейс должен включать в себя их исключения (и IDE ругается, если не включать их). А так как у меня в printTofile есть исключение, то оно и в интерфейсе остается?

2019-03-21 21:07 UTC, ujohnny commented on sem2/hw2/task3/src/main/java/Vinnik/g144/Main.java
> +            output.printSpiral(array);
а что вообще в вашем представлении полиморфизм?

2019-03-21 21:10 UTC, ujohnny commented on sem2/hw2/task3/src/main/java/Vinnik/g144/Print.java
> +    int[] printSpiral(int[][] array) throws FileNotFoundException;
ну ваш generic interface может кидать что-то типа ioexception, но  exception  конкретной реализации в общем интерфейсе присутствовать не должен

2019-03-23 08:08 UTC, katevi commented on sem2/hw2/task3/src/main/java/Vinnik/g144/Main.java
> +            output.printSpiral(array);
То, что потомки могут переопределять поведение предков, и можно получить доступ к ним по родительскому интерфейсу?

2019-04-10 13:23 UTC, jzuken commented
а тут конфликт с мастером почему-то

2019-05-04 18:18 UTC, jzuken requested changes

2019-05-04 18:18 UTC, jzuken commented on sem2/hw2/task3/src/main/java/Vinnik/g144/Spiral.java
> +    public static int[] resultArray(int[][] originalArray) {
замечание про полиморфизм тут было к тому, что в этом методе надо сразу выводить в нужное место элементы при обходе

2019-05-11 11:15 UTC, merged