Added task 2.4
katevi/Spbu-homeworks pull request #15
Opened 2018-09-27 19:43 UTC by katevi

2018-09-29 08:18 UTC, jzuken requested changes

2018-09-29 08:18 UTC, jzuken commented on sem1/hw1/Hw2t4.cpp
> +    const int _NUMBER = 10;
константы по стайлгайду именуются так же, как и переменные

2018-09-29 08:18 UTC, jzuken commented on sem1/hw1/Hw2t4.cpp
> +#include <iostream>
а этот файл тут зачем?

2018-09-29 08:18 UTC, jzuken commented on sem1/hw2/Hw2t4.cpp
> +    std::cout << "The smallest number formed by the digits of a given number:";
хотелось бы, чтобы первая цифра в числе была не 0

2018-09-29 08:42 UTC, katevi commented on sem1/hw1/Hw2t4.cpp
> +#include <iostream>
Он для std же вроде как

2018-10-06 07:28 UTC, jzuken requested changes

2018-10-06 07:28 UTC, jzuken commented on sem1/hw1/Hw2t4.cpp
> +#include <iostream>
я не про iostream, а про дубликат файла. посмотри, у тебя тут два файла: sem1/hw1/Hw2t4.cpp и sem1/hw2/Hw2t4.cpp. один явно лишний

2018-10-10 12:15 UTC, jzuken commented
оно теперь на всякий ввод выводит что-то очень длинное и неправильное

2018-10-10 17:15 UTC, closed without merging