Added Hw3t1
katevi/Spbu-homeworks pull request #170
Opened 2019-03-17 21:32 UTC by katevi

2019-04-14 14:29 UTC, ujohnny requested changes

2019-04-14 14:29 UTC, ujohnny commented on sem2/hw3/task1/Documentation.md
> +* **List class** - simple single-linked list
тут уже можно было и linkedlist/arraylist использовать

2019-04-14 14:29 UTC, ujohnny commented on sem2/hw3/task1/src/main/java/Vinnik/g144/HashTable.java
> +    void removeElement(String value) throws ListIsEmptyException;
тут какое-то несогласование, у вас из интерфейса хэш таблицы летит исключение какой то ее реализации

2019-04-14 14:29 UTC, ujohnny commented on sem2/hw3/task1/src/main/java/Vinnik/g144/Main.java
> +            table = new ListHashTable(new HashFunctionSum());
ну тут копипаста, вы сначала выберите алгоритм, а потом в одном месте создайте таблицу.

2019-04-14 14:29 UTC, ujohnny commented on sem2/hw3/task1/src/main/java/Vinnik/g144/Main.java
> +        File file = new File("/Users/Katinka/IdeaProjects/Hw3t1_gradle/src/main/java/Vinnik/g144/input.txt");
тут путь полный, у меня такое точно работать не будет

2019-04-15 17:34 UTC, katevi commented on sem2/hw3/task1/Documentation.md
> +* **List class** - simple single-linked list
По-моему, нам только на следующей паре разрешили использовать стандартные реализации:(

2019-05-02 08:01 UTC, jzuken requested changes

2019-05-02 08:01 UTC, jzuken commented on sem2/hw3/task1/src/main/java/Vinnik/g144/HashTable.java
> +public interface HashTable {
а тут доки где?

2019-05-02 08:01 UTC, jzuken commented on sem2/hw3/task1/src/main/java/Vinnik/g144/HashFunctionSum.java
> +    public int hash(String string, int mod) {
про Override не надо забывать

2019-05-02 08:01 UTC, jzuken commented on sem2/hw3/task1/src/main/java/Vinnik/g144/ListHashTable.java
> +                result++;
а почему инкремент? там же сколько элементов в списке, столько и было коллизий

2019-05-11 11:11 UTC, merged