Added Hw4t1
katevi/Spbu-homeworks pull request #171
Opened 2019-03-18 14:02 UTC by katevi

2019-04-14 14:52 UTC, ujohnny requested changes

2019-04-14 14:52 UTC, ujohnny commented on sem2/hw4/task1/src/main/java/Vinnik/g144/List.java
> +    void addElement(Type value) throws RepeatingElementException;
почему у вас тут exception специфичный для реализации в интерфейсе?

2019-05-02 08:05 UTC, jzuken requested changes

2019-05-02 08:05 UTC, jzuken commented on sem2/hw4/task1/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
не надо этот файл выкладывать

2019-05-02 08:05 UTC, jzuken commented on sem2/hw4/task1/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
и этот тоже

2019-05-02 08:05 UTC, jzuken commented on sem2/hw4/task1/src/main/java/Vinnik/g144/List.java
> +public interface List<Type> {
доки?

2019-05-02 08:05 UTC, jzuken commented on sem2/hw4/task1/src/main/java/Vinnik/g144/LinkedList.java
> +     * @param value the value of the element to add to the list
а где спецификация бросаемых исключений?

2019-05-02 08:05 UTC, jzuken commented on sem2/hw4/task1/src/main/java/Vinnik/g144/UniqueList.java
> +    public void addElement(Type value) throws RepeatingElementException {
а у этого метода другое поведение, нежели в базовом классе. это нужно отразить в документации

2019-05-11 11:12 UTC, merged