Added JavaHw2t2
katevi/Spbu-homeworks pull request #174
Opened 2019-03-22 18:20 UTC by katevi

2019-04-14 14:32 UTC, ujohnny requested changes

2019-04-14 14:32 UTC, ujohnny commented on sem2/hw2/task2/src/main/java/Vinnik/g144/Calculator.java
> +        System.out.println("Enter expression:");
почему у вас сущность калькулятор ответственна за считывание входных данных??

2019-04-14 14:32 UTC, ujohnny commented on sem2/hw2/task2/src/main/java/Vinnik/g144/Calculator.java
> +    private static Stack<Character> operations;
а зачем их два, почему нельзя хранить в одном?

2019-05-02 07:00 UTC, jzuken requested changes

2019-05-02 07:00 UTC, jzuken commented on sem2/hw2/task2/src/main/java/Vinnik/g144/ArrayStack.java
> +            doubleSize();
то есть это стек, который растёт и никогда не уменьшается?

2019-05-02 07:00 UTC, jzuken commented on sem2/hw2/task2/src/main/java/Vinnik/g144/Calculator.java
> +    private String convertToPostfix(String expression) {
это слишком длинный метод

2019-05-02 07:00 UTC, jzuken commented on sem2/hw2/task2/src/main/java/Vinnik/g144/Calculator.java
> +        Integer count = 0;
зачем он объектный? ты же дальше его как индекс используешь сугубо, там постоянный boxing-unboxing будет

2019-05-02 07:00 UTC, jzuken commented on sem2/hw2/task2/src/main/java/Vinnik/g144/Calculator.java
> +        float a = 0;
не самые удачные имена

2019-05-02 07:00 UTC, jzuken commented on sem2/hw2/task2/src/main/java/Vinnik/g144/Calculator.java
> +                result.push((float) (finalString[i]) - 48);
48?

2019-05-02 07:00 UTC, jzuken commented on sem2/hw2/task2/src/main/java/Vinnik/g144/Calculator.java
> +                    result.push(operate(b,a,finalString[i]));
пробелы

2019-05-02 07:00 UTC, jzuken commented on sem2/hw2/task2/src/main/java/Vinnik/g144/LinkedStack.java
> +    private class StackElement {
лучше утащить в конец объемлющего класса

2019-05-02 07:00 UTC, jzuken commented on sem2/hw2/task2/src/main/java/Vinnik/g144/LinkedStack.java
> +        public Type value;
лучше всё равно их спрятать

2019-05-11 11:15 UTC, jzuken requested changes

2019-05-11 11:15 UTC, jzuken commented on sem2/hw2/task2/src/main/java/Vinnik/g144/EmptyStackException.java
> +public class EmptyStackException extends RuntimeException {}
лучше сделать его проверяемым

2019-05-11 11:15 UTC, jzuken commented on sem2/hw2/task2/src/main/java/Vinnik/g144/IncorrectFormException.java
> +public class IncorrectFormException extends Throwable {
ну и тут тоже, если не знаешь от кого наследоваться, наследуйся от Exception

2019-05-11 11:15 UTC, jzuken commented on sem2/hw2/task2/src/main/java/Vinnik/g144/ArrayStack.java
> +    private final int MINIMAL_SIZE_OF_STACK = 3;
по стайлгайду капсом пишутся статические константы

2019-05-17 13:35 UTC, merged