Added Hw3t2
katevi/Spbu-homeworks pull request #175
Opened 2019-03-23 12:40 UTC by katevi

2019-04-14 14:49 UTC, ujohnny requested changes

2019-04-14 14:49 UTC, ujohnny commented on sem2/hw3/task2/src/main/java/Vinnik/g144/ExpressionTree.java
> +        int[] i = new int[1];
а что это за чудо переменная?

2019-04-14 14:49 UTC, ujohnny commented on sem2/hw3/task2/src/test/java/Vinnik/g144/ExpressionTreeTest.java
> +        String expression = "( (+ 1 1) 2)";
а если написать просто `"1"`, то не работает

2019-05-03 15:36 UTC, jzuken requested changes

2019-05-03 15:36 UTC, jzuken commented on sem2/hw3/task2/src/main/java/Vinnik/g144/Addition.java
> +public class Addition extends Operator implements Operand {
доки?

2019-05-03 15:36 UTC, jzuken commented on sem2/hw3/task2/src/main/java/Vinnik/g144/Division.java
> +        return left.calculate() / right.calculate();
мне кажется, делать по классу на каждую операцию -- перебор. но ок

2019-05-03 15:36 UTC, jzuken commented on sem2/hw3/task2/src/main/java/Vinnik/g144/Addition.java
> +package Vinnik.g144;
ну вообще, если следовать соглашению, то должно быть наоборот, g144.Vinnik

2019-05-03 15:36 UTC, jzuken commented on sem2/hw3/task2/src/main/java/Vinnik/g144/ExpressionTree.java
> +            finalExpression = finalExpression + convertExpression[i];
для этого лучше использовать StringBuilder

2019-05-03 15:36 UTC, jzuken commented on sem2/hw3/task2/src/main/java/Vinnik/g144/ExpressionTree.java
> +        while ((str.charAt(numberOfCharactersProcessed) > '0') && (str.charAt(numberOfCharactersProcessed) < '9')) {
так может сохранить этот str.charAt(numberOfCharactersProcessed) в переменную и использовать её?

2019-05-03 17:10 UTC, katevi commented on sem2/hw3/task2/src/main/java/Vinnik/g144/Addition.java
> +package Vinnik.g144;
Т.е., надо поменять в этой программе и во всех следующих на g144.Vinnik, или так можно оставить?

2019-05-04 16:28 UTC, jzuken commented on sem2/hw3/task2/src/main/java/Vinnik/g144/Addition.java
> +package Vinnik.g144;
да не, не надо менять, это на будущее

2019-05-11 11:16 UTC, merged