Added Hw4t2
katevi/Spbu-homeworks pull request #176
Opened 2019-03-26 10:27 UTC by katevi

2019-04-14 16:25 UTC, ujohnny requested changes

2019-04-14 16:25 UTC, ujohnny commented on sem2/hw4/task2/src/main/java/Vinnik/g144/BalanceTree.java
> +    void setRoot(Node<Type> node) {
а где квалификаторы доступа?

2019-04-14 16:25 UTC, ujohnny commented on sem2/hw4/task2/src/main/java/Vinnik/g144/Node.java
> +    private void rotateLeft(BalanceTree<Type> tree) {
в этой ф-и куча косяков с пробелами

2019-04-14 16:25 UTC, ujohnny commented on sem2/hw4/task2/src/main/java/Vinnik/g144/Node.java
> +        if (value.compareTo(getValue()) < 0) {
а если value == null ?

2019-04-15 20:20 UTC, katevi commented on sem2/hw4/task2/src/main/java/Vinnik/g144/Node.java
> +        if (value.compareTo(getValue()) < 0) {
Не совсем поняла. Как оно может быть null, если value - добавляемый элемент?

2019-05-04 16:22 UTC, jzuken commented on sem2/hw4/task2/src/main/java/Vinnik/g144/Node.java
> +        if (value.compareTo(getValue()) < 0) {
а что мешает вызвать addNode(), передав туда null?

2019-05-04 16:25 UTC, jzuken requested changes

2019-05-04 16:25 UTC, jzuken commented on sem2/hw4/task2/src/main/java/Vinnik/g144/Node.java
> +        if (value.compareTo(getValue()) < 0) {
и модификатор доступа тут и ниже потерялся

2019-05-04 16:25 UTC, jzuken commented on sem2/hw4/task2/src/main/java/Vinnik/g144/Node.java
> +        String result = "( " + value.toString() + " ";
для этого надо пользоваться StringBuilder'ом

2019-05-05 16:32 UTC, katevi commented on sem2/hw4/task2/src/main/java/Vinnik/g144/Node.java
> +        if (value.compareTo(getValue()) < 0) {
А для этого случая подходит исключение NullPointerException(), или лучше свое какое-то написать?

2019-05-07 08:43 UTC, jzuken commented on sem2/hw4/task2/src/main/java/Vinnik/g144/Node.java
> +        if (value.compareTo(getValue()) < 0) {
лучше IllegalArgumentException

2019-05-11 11:17 UTC, merged