2.4
katevi/Spbu-homeworks pull request #37
Opened 2018-10-10 17:15 UTC by katevi

2018-10-10 17:22 UTC, katevi commented
Вы не могли бы сказать, что именно длинное и неправильное выдается при вводе?
Просто я потестила у себя, у меня все нормально работает.

2018-10-17 16:10 UTC, jzuken requested changes

2018-10-17 16:10 UTC, jzuken commented on sem1/hw2/Hw2t4.cpp
> +	std::cout << digitsOfNumber[i];
с отступами тут какой-то фарш

2018-10-17 16:10 UTC, jzuken commented
вроде работает правильно сейчас

2018-10-27 15:22 UTC, merged