Added task 4.1
katevi/Spbu-homeworks pull request #41
Opened 2018-10-14 19:17 UTC by katevi

2018-10-22 12:12 UTC, ujohnny requested changes

2018-10-22 12:12 UTC, ujohnny commented on sem1/hw4/task1/list.h
> +#pragma once
вообще pragma once считается нестандартной вещью и в 99% случаев практически все используют include guards.

2018-10-22 12:12 UTC, ujohnny commented on sem1/hw4/task1/list.h
> +#pragma once
вообще pragma once считается нестандартной вещью и в 99% случаев практически все используют include guards.

2018-10-22 12:12 UTC, ujohnny commented on sem1/hw4/task1/list.cpp
> +void print(List *list, int n)
почему ф-я не является членом структуры?

2018-10-22 12:12 UTC, ujohnny commented on sem1/hw4/task1/list.cpp
> +		++length;
смесь 6 и 8 пробелов, выглядит странно

2018-10-22 12:12 UTC, ujohnny commented on sem1/hw4/task1/main.cpp
> +		add(list, i);
везде потеряны скобки

2018-10-22 12:12 UTC, ujohnny commented on sem1/hw4/task1/list.cpp
> +void cicle(List* list)
а почему нельзя сразу список создать цикличным?

2018-10-22 12:12 UTC, ujohnny commented on sem1/hw4/task1/list.cpp
> +	ListElement *current = list->first;
ну тут явно удалятся всего 2 элемента, а остальные будут потеряны

2018-10-22 12:12 UTC, ujohnny commented on sem1/hw4/task1/list.cpp
> +void deletingElements(List *list, int m)
форма герундия здесь неприменима

2018-10-22 12:12 UTC, ujohnny commented on sem1/hw4/task1/list.cpp
> +	while (current->next != list->first)
for(current, ..., current = ...) {}

2018-10-22 12:12 UTC, ujohnny requested changes

2018-10-22 12:12 UTC, ujohnny commented on sem1/hw4/task1/list.cpp
> +	while (i < n)
здесь тоже for

2018-10-22 13:38 UTC, jzuken commented on sem1/hw4/task1/list.cpp
> +void print(List *list, int n)
потому что я им про это не рассказывал, пусть пока так пишут :)

2018-10-23 17:24 UTC, katevi commented on sem1/hw4/task1/list.cpp
> +	ListElement *current = list->first;
Но ведь там, по-моему, в конце от списка остается всего один элемент и сам список, как там удалять еще что-то?

2018-10-23 17:44 UTC, katevi commented on sem1/hw4/task1/list.cpp
> +void cicle(List* list)
У нас был код обычного списка с пары, я сделала его цикличным. В условии вроде ничего не говорилось про способ создания циклического списка.

2018-10-24 18:07 UTC, ujohnny reviewed
скобки так и не вернулись, индентация тоже шалит

2018-10-24 18:07 UTC, ujohnny commented on sem1/hw4/task1/list.cpp
> +void cicle(List* list)
есть структура данных список, есть структура данных циклический список. почему список нельзя было реализовать сразу циклическим, чтобы вне зависимости от момента времени, он сохранял цикличность?

2018-10-24 18:07 UTC, ujohnny commented on sem1/hw4/task1/list.cpp
> +	ListElement *current = list->first;
глобально вне зависимости от входных данных результат должен соответствовать контракту, который здесь, исходя из названия удаляет список, а так как список владеет всеми его элементами, то удаляет и их

2018-10-27 15:03 UTC, jzuken requested changes

2018-10-27 15:03 UTC, jzuken commented on sem1/hw4/task1/list.cpp
> +	return new List {0, nullptr, nullptr };
пробел лишний

2018-10-27 15:03 UTC, jzuken commented on sem1/hw4/task1/list.cpp
> +	ListElement *current = new ListElement;
так его поля тоже можно проинициализировать в фигурных скобках

2018-10-27 15:03 UTC, jzuken commented on sem1/hw4/task1/list.cpp
> +	if (list->head != NULL)
лучше использовать nullptr

2018-10-27 15:03 UTC, jzuken commented on sem1/hw4/task1/list.h
> +	ListElement *tail { nullptr };
вообще тут вроде как циклический список нужен, а у него вроде никакого хвоста нет

2018-10-27 15:03 UTC, jzuken commented on sem1/hw4/task1/list.cpp
> +void deleteElements(List *list, int m)
не, вот эта логика -- это не функция модуля АТД "Список". это логика задачи, которая решается с помощью этого АТД, и поэтому должна быть в main.cpp. но реализована она должна быть так, чтобы не залазить в детали реализации модуля списка

2018-10-29 16:38 UTC, katevi commented on sem1/hw4/task1/list.cpp
> +void deleteElements(List *list, int m)
А это как - не залазить в детали реализации модуля списка? Я просто не совсем понимаю, что мне нужно в ней переделать кроме того, что переставить в main.cpp

2018-10-31 18:28 UTC, jzuken commented on sem1/hw4/task1/list.cpp
> +void deleteElements(List *list, int m)
это значит использовать только открытые функции, объявленные в заголовочном файле

2018-10-31 18:29 UTC, jzuken commented on sem1/hw4/task1/list.cpp
> +void deleteElements(List *list, int m)
ну то есть не использовать в main.cpp ListElement, например

2018-10-31 18:54 UTC, katevi commented on sem1/hw4/task1/list.cpp
> +void deleteElements(List *list, int m)
Окей, спасибо

2018-11-02 12:59 UTC, jzuken requested changes

2018-11-02 12:59 UTC, jzuken commented on sem1/hw4/task1/list.cpp
> +	ListElement *newElement = new ListElement {number, list->head};
ну так теперь оно две ячейки создаёт

2018-11-02 12:59 UTC, jzuken commented on sem1/hw4/task1/list.cpp
> +void killTheSoldier(List* list)
неудачное имя, учитывая, что модуль списка не должен знать ничего про солдат

2018-11-02 12:59 UTC, jzuken commented on sem1/hw4/task1/list.cpp
> +void changingPosition(List* list)
имя функции -- глагол

2018-11-06 13:13 UTC, merged