Added task 4.2
katevi/Spbu-homeworks pull request #42
Opened 2018-10-18 20:55 UTC by katevi

2018-10-22 16:02 UTC, ujohnny requested changes

2018-10-22 16:02 UTC, ujohnny commented on sem1/hw4/Hw4t2.cpp
> +#define _CRT_SECURE_NO_WARNINGS
это явно чтото плохое

2018-10-22 16:02 UTC, ujohnny commented on sem1/hw4/Hw4t2.cpp
> +struct subScriber {
типы данных должны называться с большой буквы

2018-10-22 16:02 UTC, ujohnny commented on sem1/hw4/Hw4t2.cpp
> +	FILE *file = fopen("Telephones.txt", "r");
а кто его закроет? и если пользуетесь iostream, то файлы тоже через него читайте

2018-10-22 16:02 UTC, ujohnny commented on sem1/hw4/Hw4t2.cpp
> +	int c;
неинициализировано

2018-10-22 16:02 UTC, ujohnny commented on sem1/hw4/Hw4t2.cpp
> +	while ((c = getc(tempFile)) != EOF) {
может быть просто скопировать файл? тут совсем неэффективно

2018-10-22 16:02 UTC, ujohnny commented on sem1/hw4/Hw4t2.cpp
> +		int i = 0;
а i тут вообще не нужно. просто 3 раза считать из файла и все

2018-10-22 16:02 UTC, ujohnny commented on sem1/hw4/Hw4t2.cpp
> +			if ((nameOfSubscriber[j] != arrayOfSubscribers[i].name[j]) || (surnameOfSubscriber[j] != arrayOfSubscribers[i].surname[j]))
слишком длинная строчка

2018-10-22 16:02 UTC, ujohnny commented on sem1/hw4/Hw4t2.cpp
> +		for (int j = 0; j < strlen(nameOfSubscriber); j++)
strlen линейная ф-я, ее никогда не надо вызывать в for

2018-10-22 16:02 UTC, ujohnny commented on sem1/hw4/Hw4t2.cpp
> +void findingName(char numberOfSubscriber[], struct subScriber arrayOfSubscribers[100])
почему 100? да и struct  тут лишнее

2018-10-22 16:02 UTC, ujohnny commented on sem1/hw4/Hw4t2.cpp
> +		std::cout << "Choose 0, 1, 2, 3 or 4!";
тут дубликация, может быть стоит использовать do...while

2018-10-22 16:03 UTC, ujohnny requested changes

2018-10-22 16:03 UTC, ujohnny commented on sem1/hw4/Hw4t2.cpp
> +		}
а если входной файл в неправильном формате оказался?

2018-10-23 16:36 UTC, katevi commented on sem1/hw4/Hw4t2.cpp
> +	FILE *file = fopen("Telephones.txt", "r");
Нам разрешили использовать iostream только для ввода и вывода.

2018-10-23 16:38 UTC, katevi commented on sem1/hw4/Hw4t2.cpp
> +#define _CRT_SECURE_NO_WARNINGS
Я спрашивала у Тимофея Александровича как можно избавиться от проблем с fopen_s, возникающих в Visual Studio и он сказал, что можно использовать эту команду.

2018-10-23 17:48 UTC, ujohnny commented on sem1/hw4/Hw4t2.cpp
> +	FILE *file = fopen("Telephones.txt", "r");
а чтение из файла и запись в файл не являются операциями ввода вывода?

2018-10-23 18:05 UTC, katevi commented on sem1/hw4/Hw4t2.cpp
> +	FILE *file = fopen("Telephones.txt", "r");
Но это же потоки:(
А мы использовали только для std::cout/std::cin

2018-10-24 18:09 UTC, ujohnny commented on sem1/hw4/Hw4t2.cpp
> +	FILE *file = fopen("Telephones.txt", "r");
иииии? при открытии файла тоже дается поток. и Тимофей сказал, что вам можно их использовать
![image](https://user-images.githubusercontent.com/759709/47451664-ff3a9980-d7d0-11e8-83af-322c7c3e1a05.png)

2018-10-24 18:09 UTC, ujohnny commented on sem1/hw4/Hw4t2.cpp
> +#define _CRT_SECURE_NO_WARNINGS
вот на потоки перепишите все и это можно будет выкинуть

2018-10-26 18:04 UTC, katevi commented on sem1/hw4/Hw4t2.cpp
> +	FILE *file = fopen("Telephones.txt", "r");
Я заменила все std::cin и std::cout на printf и scanf и устранила проблему с #define...Я уточнила у Т.А., так тоже можно он сказал.

2018-10-27 22:44 UTC, jzuken requested changes

2018-10-27 22:44 UTC, jzuken commented on sem1/hw4/Hw4t2.cpp
> +		}
этого от них пока не требуется

2018-10-27 22:44 UTC, jzuken commented on sem1/hw4/Hw4t2.cpp
> +	printf("The subscriber was successfully added into buffer. \n");
вообще файловые операции довольно долгие. скорее имеет смысл поддерживать некоторую внутреннюю структуру справочника, а по запросу сохранять уже её в файл. а постоянно бегать в файл не особо эффективно

2018-10-27 22:44 UTC, jzuken commented on sem1/hw4/Hw4t2.cpp
> +	Subscriber arrayOfSubscribers[100]{ "","" };
тут скорее список подходит

2018-11-02 10:22 UTC, jzuken commented on sem1/hw4/Hw4t2.cpp
> +	Subscriber arrayOfSubscribers[100]{ "","" };
а вообще хочется модуль, который будет называться PhoneBook. а что он реализован на списке — это детали реализации, которые никому не интересны по сути

2018-11-02 13:27 UTC, jzuken commented
сейчас на паре расскажу, как это переделать

2018-11-06 13:21 UTC, jzuken requested changes

2018-11-06 13:21 UTC, jzuken commented on sem1/hw4/list.cpp
> +	int length = strlen(name);
list.cpp:67:26: error: ‘strlen’ was not declared in this scope

2018-11-06 13:21 UTC, jzuken commented on sem1/hw4/Hw4t2.cpp
> +void toFindName(List* list)
просто findNumber

2018-11-06 13:21 UTC, jzuken commented on sem1/hw4/Hw4t2.cpp
> +	findingNameInList(list, number);
а тут findNameInList
схема именования лучше, если везде одна

2018-11-06 13:21 UTC, jzuken commented on sem1/hw4/list.cpp
> +		delete current;
а строки, которые там лежат, кто удалять будет?

2018-11-06 13:21 UTC, jzuken commented on sem1/hw4/task2/PhoneBook.cpp
> +void menu(int option, List* list)
общение с пользователем лучше оставить в main, тут это зачем?

2018-11-17 06:52 UTC, jzuken requested changes

2018-11-17 06:52 UTC, jzuken commented on sem1/hw4/task2/list.cpp
> +		delete current->name;
это массивы

2018-11-17 06:52 UTC, jzuken commented on sem1/hw4/Hw4t2.cpp
> +#include "list.h"
теперь тут по две версии файлов

2018-11-17 06:52 UTC, jzuken commented on sem1/hw4/task2/list.cpp
> +	file.open("Telephones.txt", ios::out);
лучше передавать аргументом, чтобы имя файла было только в одном месте прописано

2018-11-24 16:43 UTC, merged