Added task 5.1
katevi/Spbu-homeworks pull request #43
Opened 2018-10-23 18:45 UTC by katevi

2018-10-31 13:40 UTC, jzuken requested changes

2018-10-31 13:40 UTC, jzuken commented on sem1/hw5/Hw5t1.cpp
> +	std::cout << "Array, obtained by spiraling from the center: \n";
хорошо бы ещё оригинальный массив всё же вывести, ты же его как-то по-своему генерируешь

2018-10-31 13:40 UTC, jzuken commented on sem1/hw5/Hw5t1.cpp
> +	for (int i = 0; i < sideOfArray; i++)
вспомогательные функции не помешают

2018-10-31 16:48 UTC, katevi commented on sem1/hw5/Hw5t1.cpp
> +	std::cout << "Array, obtained by spiraling from the center: \n";
Но он же вроде один - я просто начинаю заполнять двумерный массив из левого верхнего уголка. Не очень понимаю, что делать:(

2018-10-31 18:28 UTC, jzuken commented on sem1/hw5/Hw5t1.cpp
> +	std::cout << "Array, obtained by spiraling from the center: \n";
а, ну просто в условии другое требовалось. ладно, это замечание снимается

2018-10-31 18:52 UTC, katevi commented on sem1/hw5/Hw5t1.cpp
> +	std::cout << "Array, obtained by spiraling from the center: \n";
Получается, это зачтенная задачка?:)

2018-11-01 09:39 UTC, jzuken commented on sem1/hw5/Hw5t1.cpp
> +	std::cout << "Array, obtained by spiraling from the center: \n";
да не, пусть так будет. я посмотрю остальные исправления попозже

2018-11-01 13:49 UTC, katevi commented on sem1/hw5/Hw5t1.cpp
> +	std::cout << "Array, obtained by spiraling from the center: \n";
Хорошо

2018-11-02 12:33 UTC, jzuken requested changes

2018-11-02 12:33 UTC, jzuken commented on sem1/hw5/Hw5t1.cpp
> +	for (int i = 0; i < sideOfArray; i++)
а в эту строчку я почему ткнул? потому что удаление массива в функцию хотел

2018-11-06 13:11 UTC, merged