Added task 5.3
katevi/Spbu-homeworks pull request #45
Opened 2018-10-25 18:49 UTC by katevi

2018-10-31 14:02 UTC, jzuken requested changes

2018-10-31 14:02 UTC, jzuken commented on sem1/hw5/task3/Hw5t3.cpp
> +	std::string expression;
не, не надо тут string

2018-10-31 14:02 UTC, jzuken commented on sem1/hw5/task3/Hw5t3.cpp
> +	Stack* stack = createStack();
память не всю почистила

2018-11-02 12:37 UTC, jzuken requested changes

2018-11-02 12:37 UTC, jzuken commented on sem1/hw5/task3/Hw5t3.cpp
> +		if ((int(expression[i]) > 47) && (int(expression[i]) < 58))
магические константы опять же

2018-11-02 12:37 UTC, jzuken commented on sem1/hw5/task3/Hw5t3.cpp
> +	for (int i = 0; i < strlen(expression); i++)
string.h

2018-11-02 12:37 UTC, jzuken commented on sem1/hw5/task3/Stack.cpp
> +void deleteStack(Stack* stack)
с этой функцией всё ещё что-то не так

2018-11-06 13:15 UTC, jzuken requested changes

2018-11-06 13:15 UTC, jzuken commented on sem1/hw5/task3/Stack.cpp
> +void deleteStack(Stack* stack)
ещё одна подсказка: одного delete не хватает

2018-11-07 18:03 UTC, katevi commented on sem1/hw5/task3/Stack.cpp
> +void deleteStack(Stack* stack)
Там нужен delete stack в returnе?

2018-11-08 09:38 UTC, jzuken commented on sem1/hw5/task3/Stack.cpp
> +void deleteStack(Stack* stack)
угу

2018-11-17 06:58 UTC, jzuken commented
а ничего не изменилось, делита всё ещё не хватает

2018-11-24 16:40 UTC, merged