Added task 5.4
katevi/Spbu-homeworks pull request #46
Opened 2018-10-27 09:51 UTC by katevi

2018-11-01 16:41 UTC, jzuken requested changes

2018-11-01 16:41 UTC, jzuken commented on sem1/hw5/task4/Hw5t4.cpp
> +	int lengthOfPostfixForm = strlen(postfixForm);
string.h надо подключать для использования strlen

2018-11-01 16:41 UTC, jzuken commented on sem1/hw5/task4/Hw5t4.cpp
> +		if ((float(postfixForm[i]) > 47) && (float(postfixForm[i]) < 58))
магические константы лучше в коде не использовать

2018-11-01 16:48 UTC, katevi commented on sem1/hw5/task4/Hw5t4.cpp
> +		if ((float(postfixForm[i]) > 47) && (float(postfixForm[i]) < 58))
Их надо пояснить или убрать?

2018-11-01 17:39 UTC, jzuken commented on sem1/hw5/task4/Hw5t4.cpp
> +		if ((float(postfixForm[i]) > 47) && (float(postfixForm[i]) < 58))
использовать нормальные символы вместо их кодов

2018-11-01 17:56 UTC, katevi commented on sem1/hw5/task4/Hw5t4.cpp
> +		if ((float(postfixForm[i]) > 47) && (float(postfixForm[i]) < 58))
Окей

2018-11-17 06:58 UTC, jzuken requested changes

2018-11-17 06:58 UTC, jzuken commented on sem1/hw5/task4/Stack.cpp
> +		delete stack;
это прекрасно :)

2018-11-24 16:40 UTC, merged