7.1
katevi/Spbu-homeworks pull request #51
Opened 2018-11-13 19:39 UTC by katevi

2018-11-20 10:28 UTC, jzuken commented
Choose option:5
 (1 (0 null  null)  (5 (4 (3 null  null)  null)  null) )
Choose option:2
Enter element to delete (int value):1

Choose option:5
 (5 (0 null  null)  (4 (3 null  null)  null) )

и почему так?

2018-11-20 10:29 UTC, jzuken requested changes

2018-11-20 10:29 UTC, jzuken commented on sem1/hw7/task1/BinaryTree.h
> +Node* minimumNode(Node* node);
а это всё точно нужно в публичном интерфейсе модуля?

2018-11-20 10:29 UTC, jzuken commented on sem1/hw7/task1/Hw7t1.cpp
> +	BinaryTree* tree = createTree();
по условию требовалось создать множество, а тут дерево создаётся. это другой тип данных. то, что множество реализовано на дереве -- это уже детали реализации

2018-11-24 18:32 UTC, jzuken requested changes

2018-11-24 18:32 UTC, jzuken commented on sem1/hw7/task1/BinaryTree.h
> +void removeNode(Node* &node, int x);
ещё раз: функции для работы с нодами в открытом интерфейсе модуля не нужны. вообще то, что там используются ноды -- это детали реализации, которые никому не интересны

2018-11-24 18:32 UTC, jzuken commented on sem1/hw7/task1/Set.cpp
> +void removeSet(Set* set)
ничего не забыла?

2018-11-26 10:30 UTC, katevi commented on sem1/hw7/task1/BinaryTree.h
> +void removeNode(Node* &node, int x);
Я тогда все равно не очень понимаю. Как можно реализовать множество на основе двоичного дерева, если у меня не будет реализовано само дерево? Вроде функции из BinaryTree.h нужны для Set.h :/

2018-12-04 14:27 UTC, jzuken requested changes

2018-12-04 14:27 UTC, jzuken commented on sem1/hw7/task1/Set.cpp
> +	std::cout << "Enter element to add (int value):";
не очень хорошая идея добавлять ввод-вывод в модуль работы со множеством. а если тебе понадобится в другой задаче его использовать каким-то другим образом? работа  с пользователем -- это функция основной программы

2018-12-17 16:27 UTC, merged