9.2
katevi/Spbu-homeworks pull request #74
Opened 2018-12-04 21:14 UTC by katevi

2018-12-17 16:31 UTC, ujohnny requested changes

2018-12-17 16:31 UTC, ujohnny commented on sem1/hw9/task2/BinaryTree.cpp
> +int const stringSize = 1024;
почему константа stringSize растет из binaryTree ?

2018-12-17 16:31 UTC, ujohnny commented on sem1/hw9/task2/BinaryTree.cpp
> +int const charSize = 256;
charSize всегда равен 1, как эту строчку понимать?

2018-12-17 16:31 UTC, ujohnny commented on sem1/hw9/task2/BinaryTree.cpp
> +char *outputABC(Node *node)
ф-я имеющая слово output в названии, но непроизводящяя никакого output вызывает подозрения

2018-12-17 16:31 UTC, ujohnny commented on sem1/hw9/task2/BinaryTree.cpp
> +	countCodes(node->left, codes, code * 10);
что за 10?

2018-12-17 16:31 UTC, ujohnny commented on sem1/hw9/task2/BinaryTree.cpp
> +int const stringSize = 1024;
да она еще и в двух местах определена

2018-12-17 16:31 UTC, ujohnny commented on sem1/hw9/task2/queue.cpp
> +Tree *extractMinimum(PriorityQueue *priorityQueue, int &key)
не надо передавать int по reference, такая мутабельность ухудшает понимание

2018-12-17 16:31 UTC, ujohnny commented on sem1/hw9/task2/Huffman.cpp
> +		Tree *temp = extractMinimum(queue, tempKey);
extractMinimum должен Node возвращать, а не Tree. и это называется top/pop обычно

2018-12-17 16:31 UTC, ujohnny commented on sem1/hw9/task2/Huffman.cpp
> +	int *frequency = new int[charSize];
можно и без new

2018-12-19 18:43 UTC, katevi commented on sem1/hw9/task2/Huffman.cpp
> +		Tree *temp = extractMinimum(queue, tempKey);
Но в статье на Хабре написано, что у нас очередь именно из деревьев.

2018-12-19 19:06 UTC, katevi commented on sem1/hw9/task2/Huffman.cpp
> +		Tree *temp = extractMinimum(queue, tempKey);
Почему? В статье на Хабре, которая приложена к нашему дз, автор оперирует именно с очередью из деревьев, и потом их мерджит:/

2018-12-20 07:47 UTC, katevi commented on sem1/hw9/task2/BinaryTree.cpp
> +	countCodes(node->left, codes, code * 10);
Обход по дереву и получение кода как десятичного числа, состоящего из 0 и 1.

2018-12-21 14:55 UTC, jzuken commented
закодировал файл
```
"Beep boop beer!"
adasdasd,sadsadssa
sadsd.... ... d
s a
s
```
раскодировал, а там только первая строка

2018-12-23 14:02 UTC, merged